-- Remove the unused exam cheat violation audit action.

DELETE FROM "AuditLog"
WHERE "action" = 'EXAM_CHEAT_VIOLATION'::"AuditAction";

ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";

CREATE TYPE "AuditAction" AS ENUM (
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'LOGOUT',
  'DEVICE_REGISTERED',
  'DEVICE_VERIFIED',
  'DEVICE_REMOVED',
  'OTP_SENT',
  'OTP_VERIFIED',
  'OTP_FAILED',
  'PASSWORD_RESET_REQUESTED',
  'SESSION_INVALIDATED',
  'PASSWORD_CHANGED',
  'SUBSCRIPTION_UPGRADED',
  'SUBSCRIPTION_CANCELLED',
  'SUBSCRIPTION_EXPIRED',
  'PREMIUM_GRANTED_MANUALLY',
  'PREMIUM_EXTENDED_MANUALLY',
  'PREMIUM_REVOKED_MANUALLY',
  'ADMIN_DEVICE_RESET',
  'ADMIN_FORCE_LOGOUT',
  'LEADERBOARD_SIGNAL_FLAGGED'
);

ALTER TABLE "AuditLog"
  ALTER COLUMN "action" TYPE "AuditAction"
  USING "action"::text::"AuditAction";

DROP TYPE "AuditAction_old";
