import { EXAM_TYPES, EXAM_CONFIG, SUBJECTS } from '../exams/exams.constants';

export const COLLAB_SESSION_STATUS = {
  WAITING: 'WAITING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const;

export const COLLAB_SESSION_TYPE = {
  ONE_V_ONE_DUEL: EXAM_TYPES.ONE_V_ONE_DUEL
} as const;

export const COLLAB_QUESTION_SOURCE = {
  REAL_PAST_QUESTION: 'REAL_PAST_QUESTION',
  PRACTICE: 'PRACTICE',
  MIXED: 'MIXED'
} as const;

export const PARTICIPANT_STATE = {
  JOINED: 'JOINED',
  READY: 'READY',
  DISCONNECTED: 'DISCONNECTED',
  FINISHED: 'FINISHED'
} as const;

export const COLLAB_WEBSOCKET_EVENTS = {
  PRESENCE_UPDATE: 'presence_update',
  SESSION_STARTED: 'session_started',
  SESSION_NAME_UPDATED: 'session_name_updated',
  SESSION_CANCELLED: 'session_cancelled',
  SESSION_COMPLETED: 'session_completed',
  PROGRESS_UPDATE: 'progress_update',
  TIME_ALERT: 'time_alert',
  EMOJI_REACTION: 'emoji_reaction',
  FINISHED: 'finished',
  CONNECTION_REPLACED: 'connection_replaced',
  SERVER_ERROR: 'server_error',
  READY: 'ready'
} as const;

export const COLLAB_LIMITS = {
  MAX_PARTICIPANTS_V1: 2,
  MIN_PARTICIPANTS_V1: 2,
  SESSION_CODE_LENGTH: 8,
  DEFAULT_MAX_PARTICIPANTS: 2,
  HEARTBEAT_TTL_SECONDS: 40,
  HEARTBEAT_GRACE_SECONDS: 20,
  HEARTBEAT_PING_INTERVAL_SECONDS: 15,
  START_LOCK_TTL_SECONDS: 20,
  IDEMPOTENCY_TTL_SECONDS: 86400,
  EVENT_RATE_LIMIT_WINDOW_SECONDS: 30,
  EMOJI_RATE_LIMIT_MAX: 20,
  PROGRESS_RATE_LIMIT_MAX: 120,
  TIME_ALERT_RATE_LIMIT_MAX: 40,
  QUESTIONS_PER_SUBJECT: EXAM_CONFIG.QUESTIONS_PER_SUBJECT,
  ALLOWED_SUBJECTS: SUBJECTS
} as const;
